### ISSUE TITLE
Recipes error message on terminal

### ISSUE THREAD

**Issue by eericn** [gigapath/whatthefridge#180]
It doesn't break anything, but I see the following error in my terminal window whenever the recipes tab is loaded:
Unhandled rejection TypeError: Cannot read property 'user_id' of undefined
    at randomRecipeGen (/Users/Eric/Desktop/whatthefridge/server/recipes/recipesController.js:126:42)
    at /Users/Eric/Desktop/whatthefridge/server/recipes/recipesController.js:140:18

**Comment by josh-stevens** [comment]
I think this bug is happening if you are the only user with recipes.

**Comment by eericn** [comment]
Yeah, that was it.
