### ISSUE TITLE
Saved Lists ---> shopping list

### ISSUE THREAD

**Issue by eericn** [gigapath/whatthefridge#182]
When a saved list with an ingredient containing a decimal qty is clicked, the shopping list view rounds up the qty.

**Comment by josh-stevens** [comment]
The bug is actually occuring in the saved lists controller. Need to rework this logic: 

$scope.shop = function(list) {
      Recipes.selectedRecipes = [{ingredients:[]}];
      for (var key in list) {
        if (key === 'date') continue;
        // push the ingredient once for every quantity
        for (var i = 0; i < list[key][0]; i++) {
          Recipes.selectedRecipes[0].ingredients.push(key)
        }
      }
      $location.path('shopping-list');
    }
