### ISSUE TITLE
orphaned ingredients in shopping list after deleting recipe

### ISSUE THREAD

**Issue by mishasaggi** [gigapath/whatthefridge#195]
delete recipe now deletes all dependent data in mapping table.
The shopping list still contains the ingredients from that deleted recipe, although reference to that recipe in the subheading has gone away.

Do we need to handle this?

**Comment by josh-stevens** [comment]
The recipe is gone but the ingredients remain? That's the expected behavior. The shopping list hasn't changed, just the recipe reference. Also we don't want to delete the ingredients themselves because they may be used in other recipes

**Comment by mishasaggi** [comment]
Ok, so keeping the list intact and yes, the ingredients should remain in the ing table. My question was just for the shopping list.
